package com.axonivy.utils.gdpr.enums;

public enum DocumentType implements HasCmsName  {
	ABSENCE, APPRAISAL, ARCHIVE, COMPANY_ASSETS, CONTRACT, CORRESPONDENCE, EMPLOYER_STATEMENT, EXTERNAL_PAYMENT,
	HEALTH_AND_SAFETY, INCOME_TAX, JOB_CHANGE, LABOR_LAW, LEARNING_AND_DEVELOPMENT, LEAVER, MOBILITY,
	MONTHLY_PAYROLL_DATA, NATIONAL_ID, NDA_COMPETITION_AND_RELATIONCLAUSE, PENSION_AND_INSURANCE, PERSONAL_INFORMATION,
	SALARY, SOCIAL_INSURANCE, TO_DELETE, WORK_PERMIT;
}
